//
//  BrowsingCountry.swift
//  EhPanda
//
//  Created by 荒木辰造 on R 4/01/30.
//

import Foundation

// swiftlint:disable line_length
extension EhSetting {
    enum BrowsingCountry: String, CaseIterable, Identifiable, Equatable {
        case autoDetect = "-"; case afghanistan = "AF"; case alandIslands = "AX"; case albania = "AL"; case algeria = "DZ"; case americanSamoa = "AS"; case andorra = "AD"; case angola = "AO"; case anguilla = "AI"; case antarctica = "AQ"; case antiguaAndBarbuda = "AG"; case argentina = "AR"; case armenia = "AM"; case aruba = "AW"; case asiaPacificRegion = "AP"; case australia = "AU"; case austria = "AT"; case azerbaijan = "AZ"; case bahamas = "BS"; case bahrain = "BH"; case bangladesh = "BD"; case barbados = "BB"; case belarus = "BY"; case belgium = "BE"; case belize = "BZ"; case benin = "BJ"; case bermuda = "BM"; case bhutan = "BT"; case bolivia = "BO"; case bonaireSaintEustatiusAndSaba = "BQ"; case bosniaAndHerzegovina = "BA"; case botswana = "BW"; case bouvetIsland = "BV"; case brazil = "BR"; case britishIndianOceanTerritory = "IO"; case bruneiDarussalam = "BN"; case bulgaria = "BG"; case burkinaFaso = "BF"; case burundi = "BI"; case cambodia = "KH"; case cameroon = "CM"; case canada = "CA"; case capeVerde = "CV"; case caymanIslands = "KY"; case centralAfricanRepublic = "CF"; case chad = "TD"; case chile = "CL"; case china = "CN"; case christmasIsland = "CX"; case cocosIslands = "CC"; case colombia = "CO"; case comoros = "KM"; case congo = "CG"; case theDemocraticRepublicOfTheCongo = "CD"; case cookIslands = "CK"; case costaRica = "CR"; case coteDIvoire = "CI"; case croatia = "HR"; case cuba = "CU"; case curacao = "CW"; case cyprus = "CY"; case czechRepublic = "CZ"; case denmark = "DK"; case djibouti = "DJ"; case dominica = "DM"; case dominicanRepublic = "DO"; case ecuador = "EC"; case egypt = "EG"; case elSalvador = "SV"; case equatorialGuinea = "GQ"; case eritrea = "ER"; case estonia = "EE"; case ethiopia = "ET"; case europe = "EU"; case falklandIslands = "FK"; case faroeIslands = "FO"; case fiji = "FJ"; case finland = "FI"; case france = "FR"; case frenchGuiana = "GF"; case frenchPolynesia = "PF"; case frenchSouthernTerritories = "TF"; case gabon = "GA"; case gambia = "GM"; case georgia = "GE"; case germany = "DE"; case ghana = "GH"; case gibraltar = "GI"; case greece = "GR"; case greenland = "GL"; case grenada = "GD"; case guadeloupe = "GP"; case guam = "GU"; case guatemala = "GT"; case guernsey = "GG"; case guinea = "GN"; case guineaBissau = "GW"; case guyana = "GY"; case haiti = "HT"; case heardIslandAndMcDonaldIslands = "HM"; case vaticanCityState = "VA"; case honduras = "HN"; case hongKong = "HK"; case hungary = "HU"; case iceland = "IS"; case india = "IN"; case indonesia = "ID"; case iran = "IR"; case iraq = "IQ"; case ireland = "IE"; case isleOfMan = "IM"; case israel = "IL"; case italy = "IT"; case jamaica = "JM"; case japan = "JP"; case jersey = "JE"; case jordan = "JO"; case kazakhstan = "KZ"; case kenya = "KE"; case kiribati = "KI"; case kuwait = "KW"; case kyrgyzstan = "KG"; case laoPeoplesDemocraticRepublic = "LA"; case latvia = "LV"; case lebanon = "LB"; case lesotho = "LS"; case liberia = "LR"; case libya = "LY"; case liechtenstein = "LI"; case lithuania = "LT"; case luxembourg = "LU"; case macau = "MO"; case macedonia = "MK"; case madagascar = "MG"; case malawi = "MW"; case malaysia = "MY"; case maldives = "MV"; case mali = "ML"; case malta = "MT"; case marshallIslands = "MH"; case martinique = "MQ"; case mauritania = "MR"; case mauritius = "MU"; case mayotte = "YT"; case mexico = "MX"; case micronesia = "FM"; case moldova = "MD"; case monaco = "MC"; case mongolia = "MN"; case montenegro = "ME"; case montserrat = "MS"; case morocco = "MA"; case mozambique = "MZ"; case myanmar = "MM"; case namibia = "NA"; case nauru = "NR"; case nepal = "NP"; case netherlands = "NL"; case newCaledonia = "NC"; case newZealand = "NZ"; case nicaragua = "NI"; case niger = "NE"; case nigeria = "NG"; case niue = "NU"; case norfolkIsland = "NF"; case northKorea = "KP"; case northernMarianaIslands = "MP"; case norway = "NO"; case oman = "OM"; case pakistan = "PK"; case palau = "PW"; case palestinianTerritory = "PS"; case panama = "PA"; case papuaNewGuinea = "PG"; case paraguay = "PY"; case peru = "PE"; case philippines = "PH"; case pitcairnIslands = "PN"; case poland = "PL"; case portugal = "PT"; case puertoRico = "PR"; case qatar = "QA"; case reunion = "RE"; case romania = "RO"; case russianFederation = "RU"; case rwanda = "RW"; case saintBarthelemy = "BL"; case saintHelena = "SH"; case saintKittsAndNevis = "KN"; case saintLucia = "LC"; case saintMartin = "MF"; case saintPierreAndMiquelon = "PM"; case saintVincentAndTheGrenadines = "VC"; case samoa = "WS"; case sanMarino = "SM"; case saoTomeAndPrincipe = "ST"; case saudiArabia = "SA"; case senegal = "SN"; case serbia = "RS"; case seychelles = "SC"; case sierraLeone = "SL"; case singapore = "SG"; case sintMaarten = "SX"; case slovakia = "SK"; case slovenia = "SI"; case solomonIslands = "SB"; case somalia = "SO"; case southAfrica = "ZA"; case southGeorgiaAndTheSouthSandwichIslands = "GS"; case southKorea = "KR"; case southSudan = "SS"; case spain = "ES"; case sriLanka = "LK"; case sudan = "SD"; case suriname = "SR"; case svalbardAndJanMayen = "SJ"; case swaziland = "SZ"; case sweden = "SE"; case switzerland = "CH"; case syrianArabRepublic = "SY"; case taiwan = "TW"; case tajikistan = "TJ"; case tanzania = "TZ"; case thailand = "TH"; case timorLeste = "TL"; case togo = "TG"; case tokelau = "TK"; case tonga = "TO"; case trinidadAndTobago = "TT"; case tunisia = "TN"; case turkey = "TR"; case turkmenistan = "TM"; case turksAndCaicosIslands = "TC"; case tuvalu = "TV"; case uganda = "UG"; case ukraine = "UA"; case unitedArabEmirates = "AE"; case unitedKingdom = "GB"; case unitedStates = "US"; case unitedStatesMinorOutlyingIslands = "UM"; case uruguay = "UY"; case uzbekistan = "UZ"; case vanuatu = "VU"; case venezuela = "VE"; case vietnam = "VN"; case virginIslandsBritish = "VG"; case virginIslandsUS = "VI"; case wallisAndFutuna = "WF"; case westernSahara = "EH"; case yemen = "YE"; case zambia = "ZM"; case zimbabwe = "ZW"
    }
}
// swiftlint:enable line_length
extension EhSetting.BrowsingCountry {
    var id: Int { hashValue }
    var name: String {
        switch self {
        case .autoDetect:
            return R.string.localizable.enumBrowsingCountryNameAutoDetect()
        case .afghanistan:
            return R.string.localizable.enumBrowsingCountryNameAfghanistan()
        case .alandIslands:
            return R.string.localizable.enumBrowsingCountryNameAlandIslands()
        case .albania:
            return R.string.localizable.enumBrowsingCountryNameAlbania()
        case .algeria:
            return R.string.localizable.enumBrowsingCountryNameAlgeria()
        case .americanSamoa:
            return R.string.localizable.enumBrowsingCountryNameAmericanSamoa()
        case .andorra:
            return R.string.localizable.enumBrowsingCountryNameAndorra()
        case .angola:
            return R.string.localizable.enumBrowsingCountryNameAngola()
        case .anguilla:
            return R.string.localizable.enumBrowsingCountryNameAnguilla()
        case .antarctica:
            return R.string.localizable.enumBrowsingCountryNameAntarctica()
        case .antiguaAndBarbuda:
            return R.string.localizable.enumBrowsingCountryNameAntiguaAndBarbuda()
        case .argentina:
            return R.string.localizable.enumBrowsingCountryNameArgentina()
        case .armenia:
            return R.string.localizable.enumBrowsingCountryNameArmenia()
        case .aruba:
            return R.string.localizable.enumBrowsingCountryNameAruba()
        case .asiaPacificRegion:
            return R.string.localizable.enumBrowsingCountryNameAsiaPacificRegion()
        case .australia:
            return R.string.localizable.enumBrowsingCountryNameAustralia()
        case .austria:
            return R.string.localizable.enumBrowsingCountryNameAustria()
        case .azerbaijan:
            return R.string.localizable.enumBrowsingCountryNameAzerbaijan()
        case .bahamas:
            return R.string.localizable.enumBrowsingCountryNameBahamas()
        case .bahrain:
            return R.string.localizable.enumBrowsingCountryNameBahrain()
        case .bangladesh:
            return R.string.localizable.enumBrowsingCountryNameBangladesh()
        case .barbados:
            return R.string.localizable.enumBrowsingCountryNameBarbados()
        case .belarus:
            return R.string.localizable.enumBrowsingCountryNameBelarus()
        case .belgium:
            return R.string.localizable.enumBrowsingCountryNameBelgium()
        case .belize:
            return R.string.localizable.enumBrowsingCountryNameBelize()
        case .benin:
            return R.string.localizable.enumBrowsingCountryNameBenin()
        case .bermuda:
            return R.string.localizable.enumBrowsingCountryNameBermuda()
        case .bhutan:
            return R.string.localizable.enumBrowsingCountryNameBhutan()
        case .bolivia:
            return R.string.localizable.enumBrowsingCountryNameBolivia()
        case .bonaireSaintEustatiusAndSaba:
            return R.string.localizable.enumBrowsingCountryNameBonaireSaintEustatiusAndSaba()
        case .bosniaAndHerzegovina:
            return R.string.localizable.enumBrowsingCountryNameBosniaAndHerzegovina()
        case .botswana:
            return R.string.localizable.enumBrowsingCountryNameBotswana()
        case .bouvetIsland:
            return R.string.localizable.enumBrowsingCountryNameBouvetIsland()
        case .brazil:
            return R.string.localizable.enumBrowsingCountryNameBrazil()
        case .britishIndianOceanTerritory:
            return R.string.localizable.enumBrowsingCountryNameBritishIndianOceanTerritory()
        case .bruneiDarussalam:
            return R.string.localizable.enumBrowsingCountryNameBruneiDarussalam()
        case .bulgaria:
            return R.string.localizable.enumBrowsingCountryNameBulgaria()
        case .burkinaFaso:
            return R.string.localizable.enumBrowsingCountryNameBurkinaFaso()
        case .burundi:
            return R.string.localizable.enumBrowsingCountryNameBurundi()
        case .cambodia:
            return R.string.localizable.enumBrowsingCountryNameCambodia()
        case .cameroon:
            return R.string.localizable.enumBrowsingCountryNameCameroon()
        case .canada:
            return R.string.localizable.enumBrowsingCountryNameCanada()
        case .capeVerde:
            return R.string.localizable.enumBrowsingCountryNameCapeVerde()
        case .caymanIslands:
            return R.string.localizable.enumBrowsingCountryNameCaymanIslands()
        case .centralAfricanRepublic:
            return R.string.localizable.enumBrowsingCountryNameCentralAfricanRepublic()
        case .chad:
            return R.string.localizable.enumBrowsingCountryNameChad()
        case .chile:
            return R.string.localizable.enumBrowsingCountryNameChile()
        case .china:
            return R.string.localizable.enumBrowsingCountryNameChina()
        case .christmasIsland:
            return R.string.localizable.enumBrowsingCountryNameChristmasIsland()
        case .cocosIslands:
            return R.string.localizable.enumBrowsingCountryNameCocosIslands()
        case .colombia:
            return R.string.localizable.enumBrowsingCountryNameColombia()
        case .comoros:
            return R.string.localizable.enumBrowsingCountryNameComoros()
        case .congo:
            return R.string.localizable.enumBrowsingCountryNameCongo()
        case .theDemocraticRepublicOfTheCongo:
            return R.string.localizable.enumBrowsingCountryNameTheDemocraticRepublicOfTheCongo()
        case .cookIslands:
            return R.string.localizable.enumBrowsingCountryNameCookIslands()
        case .costaRica:
            return R.string.localizable.enumBrowsingCountryNameCostaRica()
        case .coteDIvoire:
            return R.string.localizable.enumBrowsingCountryNameCoteDIvoire()
        case .croatia:
            return R.string.localizable.enumBrowsingCountryNameCroatia()
        case .cuba:
            return R.string.localizable.enumBrowsingCountryNameCuba()
        case .curacao:
            return R.string.localizable.enumBrowsingCountryNameCuracao()
        case .cyprus:
            return R.string.localizable.enumBrowsingCountryNameCyprus()
        case .czechRepublic:
            return R.string.localizable.enumBrowsingCountryNameCzechRepublic()
        case .denmark:
            return R.string.localizable.enumBrowsingCountryNameDenmark()
        case .djibouti:
            return R.string.localizable.enumBrowsingCountryNameDjibouti()
        case .dominica:
            return R.string.localizable.enumBrowsingCountryNameDominica()
        case .dominicanRepublic:
            return R.string.localizable.enumBrowsingCountryNameDominicanRepublic()
        case .ecuador:
            return R.string.localizable.enumBrowsingCountryNameEcuador()
        case .egypt:
            return R.string.localizable.enumBrowsingCountryNameEgypt()
        case .elSalvador:
            return R.string.localizable.enumBrowsingCountryNameElSalvador()
        case .equatorialGuinea:
            return R.string.localizable.enumBrowsingCountryNameEquatorialGuinea()
        case .eritrea:
            return R.string.localizable.enumBrowsingCountryNameEritrea()
        case .estonia:
            return R.string.localizable.enumBrowsingCountryNameEstonia()
        case .ethiopia:
            return R.string.localizable.enumBrowsingCountryNameEthiopia()
        case .europe:
            return R.string.localizable.enumBrowsingCountryNameEurope()
        case .falklandIslands:
            return R.string.localizable.enumBrowsingCountryNameFalklandIslands()
        case .faroeIslands:
            return R.string.localizable.enumBrowsingCountryNameFaroeIslands()
        case .fiji:
            return R.string.localizable.enumBrowsingCountryNameFiji()
        case .finland:
            return R.string.localizable.enumBrowsingCountryNameFinland()
        case .france:
            return R.string.localizable.enumBrowsingCountryNameFrance()
        case .frenchGuiana:
            return R.string.localizable.enumBrowsingCountryNameFrenchGuiana()
        case .frenchPolynesia:
            return R.string.localizable.enumBrowsingCountryNameFrenchPolynesia()
        case .frenchSouthernTerritories:
            return R.string.localizable.enumBrowsingCountryNameFrenchSouthernTerritories()
        case .gabon:
            return R.string.localizable.enumBrowsingCountryNameGabon()
        case .gambia:
            return R.string.localizable.enumBrowsingCountryNameGambia()
        case .georgia:
            return R.string.localizable.enumBrowsingCountryNameGeorgia()
        case .germany:
            return R.string.localizable.enumBrowsingCountryNameGermany()
        case .ghana:
            return R.string.localizable.enumBrowsingCountryNameGhana()
        case .gibraltar:
            return R.string.localizable.enumBrowsingCountryNameGibraltar()
        case .greece:
            return R.string.localizable.enumBrowsingCountryNameGreece()
        case .greenland:
            return R.string.localizable.enumBrowsingCountryNameGreenland()
        case .grenada:
            return R.string.localizable.enumBrowsingCountryNameGrenada()
        case .guadeloupe:
            return R.string.localizable.enumBrowsingCountryNameGuadeloupe()
        case .guam:
            return R.string.localizable.enumBrowsingCountryNameGuam()
        case .guatemala:
            return R.string.localizable.enumBrowsingCountryNameGuatemala()
        case .guernsey:
            return R.string.localizable.enumBrowsingCountryNameGuernsey()
        case .guinea:
            return R.string.localizable.enumBrowsingCountryNameGuinea()
        case .guineaBissau:
            return R.string.localizable.enumBrowsingCountryNameGuineaBissau()
        case .guyana:
            return R.string.localizable.enumBrowsingCountryNameGuyana()
        case .haiti:
            return R.string.localizable.enumBrowsingCountryNameHaiti()
        case .heardIslandAndMcDonaldIslands:
            return R.string.localizable.enumBrowsingCountryNameHeardIslandAndMcDonaldIslands()
        case .vaticanCityState:
            return R.string.localizable.enumBrowsingCountryNameVaticanCityState()
        case .honduras:
            return R.string.localizable.enumBrowsingCountryNameHonduras()
        case .hongKong:
            return R.string.localizable.enumBrowsingCountryNameHongKong()
        case .hungary:
            return R.string.localizable.enumBrowsingCountryNameHungary()
        case .iceland:
            return R.string.localizable.enumBrowsingCountryNameIceland()
        case .india:
            return R.string.localizable.enumBrowsingCountryNameIndia()
        case .indonesia:
            return R.string.localizable.enumBrowsingCountryNameIndonesia()
        case .iran:
            return R.string.localizable.enumBrowsingCountryNameIran()
        case .iraq:
            return R.string.localizable.enumBrowsingCountryNameIraq()
        case .ireland:
            return R.string.localizable.enumBrowsingCountryNameIreland()
        case .isleOfMan:
            return R.string.localizable.enumBrowsingCountryNameIsleOfMan()
        case .israel:
            return R.string.localizable.enumBrowsingCountryNameIsrael()
        case .italy:
            return R.string.localizable.enumBrowsingCountryNameItaly()
        case .jamaica:
            return R.string.localizable.enumBrowsingCountryNameJamaica()
        case .japan:
            return R.string.localizable.enumBrowsingCountryNameJapan()
        case .jersey:
            return R.string.localizable.enumBrowsingCountryNameJersey()
        case .jordan:
            return R.string.localizable.enumBrowsingCountryNameJordan()
        case .kazakhstan:
            return R.string.localizable.enumBrowsingCountryNameKazakhstan()
        case .kenya:
            return R.string.localizable.enumBrowsingCountryNameKenya()
        case .kiribati:
            return R.string.localizable.enumBrowsingCountryNameKiribati()
        case .kuwait:
            return R.string.localizable.enumBrowsingCountryNameKuwait()
        case .kyrgyzstan:
            return R.string.localizable.enumBrowsingCountryNameKyrgyzstan()
        case .laoPeoplesDemocraticRepublic:
            return R.string.localizable.enumBrowsingCountryNameLaoPeoplesDemocraticRepublic()
        case .latvia:
            return R.string.localizable.enumBrowsingCountryNameLatvia()
        case .lebanon:
            return R.string.localizable.enumBrowsingCountryNameLebanon()
        case .lesotho:
            return R.string.localizable.enumBrowsingCountryNameLesotho()
        case .liberia:
            return R.string.localizable.enumBrowsingCountryNameLiberia()
        case .libya:
            return R.string.localizable.enumBrowsingCountryNameLibya()
        case .liechtenstein:
            return R.string.localizable.enumBrowsingCountryNameLiechtenstein()
        case .lithuania:
            return R.string.localizable.enumBrowsingCountryNameLithuania()
        case .luxembourg:
            return R.string.localizable.enumBrowsingCountryNameLuxembourg()
        case .macau:
            return R.string.localizable.enumBrowsingCountryNameMacau()
        case .macedonia:
            return R.string.localizable.enumBrowsingCountryNameMacedonia()
        case .madagascar:
            return R.string.localizable.enumBrowsingCountryNameMadagascar()
        case .malawi:
            return R.string.localizable.enumBrowsingCountryNameMalawi()
        case .malaysia:
            return R.string.localizable.enumBrowsingCountryNameMalaysia()
        case .maldives:
            return R.string.localizable.enumBrowsingCountryNameMaldives()
        case .mali:
            return R.string.localizable.enumBrowsingCountryNameMali()
        case .malta:
            return R.string.localizable.enumBrowsingCountryNameMalta()
        case .marshallIslands:
            return R.string.localizable.enumBrowsingCountryNameMarshallIslands()
        case .martinique:
            return R.string.localizable.enumBrowsingCountryNameMartinique()
        case .mauritania:
            return R.string.localizable.enumBrowsingCountryNameMauritania()
        case .mauritius:
            return R.string.localizable.enumBrowsingCountryNameMauritius()
        case .mayotte:
            return R.string.localizable.enumBrowsingCountryNameMayotte()
        case .mexico:
            return R.string.localizable.enumBrowsingCountryNameMexico()
        case .micronesia:
            return R.string.localizable.enumBrowsingCountryNameMicronesia()
        case .moldova:
            return R.string.localizable.enumBrowsingCountryNameMoldova()
        case .monaco:
            return R.string.localizable.enumBrowsingCountryNameMonaco()
        case .mongolia:
            return R.string.localizable.enumBrowsingCountryNameMongolia()
        case .montenegro:
            return R.string.localizable.enumBrowsingCountryNameMontenegro()
        case .montserrat:
            return R.string.localizable.enumBrowsingCountryNameMontserrat()
        case .morocco:
            return R.string.localizable.enumBrowsingCountryNameMorocco()
        case .mozambique:
            return R.string.localizable.enumBrowsingCountryNameMozambique()
        case .myanmar:
            return R.string.localizable.enumBrowsingCountryNameMyanmar()
        case .namibia:
            return R.string.localizable.enumBrowsingCountryNameNamibia()
        case .nauru:
            return R.string.localizable.enumBrowsingCountryNameNauru()
        case .nepal:
            return R.string.localizable.enumBrowsingCountryNameNepal()
        case .netherlands:
            return R.string.localizable.enumBrowsingCountryNameNetherlands()
        case .newCaledonia:
            return R.string.localizable.enumBrowsingCountryNameNewCaledonia()
        case .newZealand:
            return R.string.localizable.enumBrowsingCountryNameNewZealand()
        case .nicaragua:
            return R.string.localizable.enumBrowsingCountryNameNicaragua()
        case .niger:
            return R.string.localizable.enumBrowsingCountryNameNiger()
        case .nigeria:
            return R.string.localizable.enumBrowsingCountryNameNigeria()
        case .niue:
            return R.string.localizable.enumBrowsingCountryNameNiue()
        case .norfolkIsland:
            return R.string.localizable.enumBrowsingCountryNameNorfolkIsland()
        case .northKorea:
            return R.string.localizable.enumBrowsingCountryNameNorthKorea()
        case .northernMarianaIslands:
            return R.string.localizable.enumBrowsingCountryNameNorthernMarianaIslands()
        case .norway:
            return R.string.localizable.enumBrowsingCountryNameNorway()
        case .oman:
            return R.string.localizable.enumBrowsingCountryNameOman()
        case .pakistan:
            return R.string.localizable.enumBrowsingCountryNamePakistan()
        case .palau:
            return R.string.localizable.enumBrowsingCountryNamePalau()
        case .palestinianTerritory:
            return R.string.localizable.enumBrowsingCountryNamePalestinianTerritory()
        case .panama:
            return R.string.localizable.enumBrowsingCountryNamePanama()
        case .papuaNewGuinea:
            return R.string.localizable.enumBrowsingCountryNamePapuaNewGuinea()
        case .paraguay:
            return R.string.localizable.enumBrowsingCountryNameParaguay()
        case .peru:
            return R.string.localizable.enumBrowsingCountryNamePeru()
        case .philippines:
            return R.string.localizable.enumBrowsingCountryNamePhilippines()
        case .pitcairnIslands:
            return R.string.localizable.enumBrowsingCountryNamePitcairnIslands()
        case .poland:
            return R.string.localizable.enumBrowsingCountryNamePoland()
        case .portugal:
            return R.string.localizable.enumBrowsingCountryNamePortugal()
        case .puertoRico:
            return R.string.localizable.enumBrowsingCountryNamePuertoRico()
        case .qatar:
            return R.string.localizable.enumBrowsingCountryNameQatar()
        case .reunion:
            return R.string.localizable.enumBrowsingCountryNameReunion()
        case .romania:
            return R.string.localizable.enumBrowsingCountryNameRomania()
        case .russianFederation:
            return R.string.localizable.enumBrowsingCountryNameRussianFederation()
        case .rwanda:
            return R.string.localizable.enumBrowsingCountryNameRwanda()
        case .saintBarthelemy:
            return R.string.localizable.enumBrowsingCountryNameSaintBarthelemy()
        case .saintHelena:
            return R.string.localizable.enumBrowsingCountryNameSaintHelena()
        case .saintKittsAndNevis:
            return R.string.localizable.enumBrowsingCountryNameSaintKittsAndNevis()
        case .saintLucia:
            return R.string.localizable.enumBrowsingCountryNameSaintLucia()
        case .saintMartin:
            return R.string.localizable.enumBrowsingCountryNameSaintMartin()
        case .saintPierreAndMiquelon:
            return R.string.localizable.enumBrowsingCountryNameSaintPierreAndMiquelon()
        case .saintVincentAndTheGrenadines:
            return R.string.localizable.enumBrowsingCountryNameSaintVincentAndTheGrenadines()
        case .samoa:
            return R.string.localizable.enumBrowsingCountryNameSamoa()
        case .sanMarino:
            return R.string.localizable.enumBrowsingCountryNameSanMarino()
        case .saoTomeAndPrincipe:
            return R.string.localizable.enumBrowsingCountryNameSaoTomeAndPrincipe()
        case .saudiArabia:
            return R.string.localizable.enumBrowsingCountryNameSaudiArabia()
        case .senegal:
            return R.string.localizable.enumBrowsingCountryNameSenegal()
        case .serbia:
            return R.string.localizable.enumBrowsingCountryNameSerbia()
        case .seychelles:
            return R.string.localizable.enumBrowsingCountryNameSeychelles()
        case .sierraLeone:
            return R.string.localizable.enumBrowsingCountryNameSierraLeone()
        case .singapore:
            return R.string.localizable.enumBrowsingCountryNameSingapore()
        case .sintMaarten:
            return R.string.localizable.enumBrowsingCountryNameSintMaarten()
        case .slovakia:
            return R.string.localizable.enumBrowsingCountryNameSlovakia()
        case .slovenia:
            return R.string.localizable.enumBrowsingCountryNameSlovenia()
        case .solomonIslands:
            return R.string.localizable.enumBrowsingCountryNameSolomonIslands()
        case .somalia:
            return R.string.localizable.enumBrowsingCountryNameSomalia()
        case .southAfrica:
            return R.string.localizable.enumBrowsingCountryNameSouthAfrica()
        case .southGeorgiaAndTheSouthSandwichIslands:
            return R.string.localizable.enumBrowsingCountryNameSouthGeorgiaAndTheSouthSandwichIslands()
        case .southKorea:
            return R.string.localizable.enumBrowsingCountryNameSouthKorea()
        case .southSudan:
            return R.string.localizable.enumBrowsingCountryNameSouthSudan()
        case .spain:
            return R.string.localizable.enumBrowsingCountryNameSpain()
        case .sriLanka:
            return R.string.localizable.enumBrowsingCountryNameSriLanka()
        case .sudan:
            return R.string.localizable.enumBrowsingCountryNameSudan()
        case .suriname:
            return R.string.localizable.enumBrowsingCountryNameSuriname()
        case .svalbardAndJanMayen:
            return R.string.localizable.enumBrowsingCountryNameSvalbardAndJanMayen()
        case .swaziland:
            return R.string.localizable.enumBrowsingCountryNameSwaziland()
        case .sweden:
            return R.string.localizable.enumBrowsingCountryNameSweden()
        case .switzerland:
            return R.string.localizable.enumBrowsingCountryNameSwitzerland()
        case .syrianArabRepublic:
            return R.string.localizable.enumBrowsingCountryNameSyrianArabRepublic()
        case .taiwan:
            return R.string.localizable.enumBrowsingCountryNameTaiwan()
        case .tajikistan:
            return R.string.localizable.enumBrowsingCountryNameTajikistan()
        case .tanzania:
            return R.string.localizable.enumBrowsingCountryNameTanzania()
        case .thailand:
            return R.string.localizable.enumBrowsingCountryNameThailand()
        case .timorLeste:
            return R.string.localizable.enumBrowsingCountryNameTimorLeste()
        case .togo:
            return R.string.localizable.enumBrowsingCountryNameTogo()
        case .tokelau:
            return R.string.localizable.enumBrowsingCountryNameTokelau()
        case .tonga:
            return R.string.localizable.enumBrowsingCountryNameTonga()
        case .trinidadAndTobago:
            return R.string.localizable.enumBrowsingCountryNameTrinidadAndTobago()
        case .tunisia:
            return R.string.localizable.enumBrowsingCountryNameTunisia()
        case .turkey:
            return R.string.localizable.enumBrowsingCountryNameTurkey()
        case .turkmenistan:
            return R.string.localizable.enumBrowsingCountryNameTurkmenistan()
        case .turksAndCaicosIslands:
            return R.string.localizable.enumBrowsingCountryNameTurksAndCaicosIslands()
        case .tuvalu:
            return R.string.localizable.enumBrowsingCountryNameTuvalu()
        case .uganda:
            return R.string.localizable.enumBrowsingCountryNameUganda()
        case .ukraine:
            return R.string.localizable.enumBrowsingCountryNameUkraine()
        case .unitedArabEmirates:
            return R.string.localizable.enumBrowsingCountryNameUnitedArabEmirates()
        case .unitedKingdom:
            return R.string.localizable.enumBrowsingCountryNameUnitedKingdom()
        case .unitedStates:
            return R.string.localizable.enumBrowsingCountryNameUnitedStates()
        case .unitedStatesMinorOutlyingIslands:
            return R.string.localizable.enumBrowsingCountryNameUnitedStatesMinorOutlyingIslands()
        case .uruguay:
            return R.string.localizable.enumBrowsingCountryNameUruguay()
        case .uzbekistan:
            return R.string.localizable.enumBrowsingCountryNameUzbekistan()
        case .vanuatu:
            return R.string.localizable.enumBrowsingCountryNameVanuatu()
        case .venezuela:
            return R.string.localizable.enumBrowsingCountryNameVenezuela()
        case .vietnam:
            return R.string.localizable.enumBrowsingCountryNameVietnam()
        case .virginIslandsBritish:
            return R.string.localizable.enumBrowsingCountryNameVirginIslandsBritish()
        case .virginIslandsUS:
            return R.string.localizable.enumBrowsingCountryNameVirginIslandsUS()
        case .wallisAndFutuna:
            return R.string.localizable.enumBrowsingCountryNameWallisAndFutuna()
        case .westernSahara:
            return R.string.localizable.enumBrowsingCountryNameWesternSahara()
        case .yemen:
            return R.string.localizable.enumBrowsingCountryNameYemen()
        case .zambia:
            return R.string.localizable.enumBrowsingCountryNameZambia()
        case .zimbabwe:
            return R.string.localizable.enumBrowsingCountryNameZimbabwe()
        }
    }
}
