import Foundation
import Resources

// reason: the exhaustive ISO country list is kept dense, one case per line
// swiftlint:disable line_length
extension EhSetting {
    public enum BrowsingCountry: String, CaseIterable, Identifiable, Equatable, Sendable {
        case autoDetect = "-"; case afghanistan = "AF"; case alandIslands = "AX"; case albania = "AL"; case algeria = "DZ"; case americanSamoa = "AS"; case andorra = "AD"; case angola = "AO"; case anguilla = "AI"; case antarctica = "AQ"; case antiguaAndBarbuda = "AG"; case argentina = "AR"; case armenia = "AM"; case aruba = "AW"; case asiaPacificRegion = "AP"; case australia = "AU"; case austria = "AT"; case azerbaijan = "AZ"; case bahamas = "BS"; case bahrain = "BH"; case bangladesh = "BD"; case barbados = "BB"; case belarus = "BY"; case belgium = "BE"; case belize = "BZ"; case benin = "BJ"; case bermuda = "BM"; case bhutan = "BT"; case bolivia = "BO"; case bonaireSaintEustatiusAndSaba = "BQ"; case bosniaAndHerzegovina = "BA"; case botswana = "BW"; case bouvetIsland = "BV"; case brazil = "BR"; case britishIndianOceanTerritory = "IO"; case bruneiDarussalam = "BN"; case bulgaria = "BG"; case burkinaFaso = "BF"; case burundi = "BI"; case cambodia = "KH"; case cameroon = "CM"; case canada = "CA"; case capeVerde = "CV"; case caymanIslands = "KY"; case centralAfricanRepublic = "CF"; case chad = "TD"; case chile = "CL"; case china = "CN"; case christmasIsland = "CX"; case cocosIslands = "CC"; case colombia = "CO"; case comoros = "KM"; case congo = "CG"; case theDemocraticRepublicOfTheCongo = "CD"; case cookIslands = "CK"; case costaRica = "CR"; case coteDIvoire = "CI"; case croatia = "HR"; case cuba = "CU"; case curacao = "CW"; case cyprus = "CY"; case czechRepublic = "CZ"; case denmark = "DK"; case djibouti = "DJ"; case dominica = "DM"; case dominicanRepublic = "DO"; case ecuador = "EC"; case egypt = "EG"; case elSalvador = "SV"; case equatorialGuinea = "GQ"; case eritrea = "ER"; case estonia = "EE"; case ethiopia = "ET"; case europe = "EU"; case falklandIslands = "FK"; case faroeIslands = "FO"; case fiji = "FJ"; case finland = "FI"; case france = "FR"; case frenchGuiana = "GF"; case frenchPolynesia = "PF"; case frenchSouthernTerritories = "TF"; case gabon = "GA"; case gambia = "GM"; case georgia = "GE"; case germany = "DE"; case ghana = "GH"; case gibraltar = "GI"; case greece = "GR"; case greenland = "GL"; case grenada = "GD"; case guadeloupe = "GP"; case guam = "GU"; case guatemala = "GT"; case guernsey = "GG"; case guinea = "GN"; case guineaBissau = "GW"; case guyana = "GY"; case haiti = "HT"; case heardIslandAndMcDonaldIslands = "HM"; case vaticanCityState = "VA"; case honduras = "HN"; case hongKong = "HK"; case hungary = "HU"; case iceland = "IS"; case india = "IN"; case indonesia = "ID"; case iran = "IR"; case iraq = "IQ"; case ireland = "IE"; case isleOfMan = "IM"; case israel = "IL"; case italy = "IT"; case jamaica = "JM"; case japan = "JP"; case jersey = "JE"; case jordan = "JO"; case kazakhstan = "KZ"; case kenya = "KE"; case kiribati = "KI"; case kuwait = "KW"; case kyrgyzstan = "KG"; case laoPeoplesDemocraticRepublic = "LA"; case latvia = "LV"; case lebanon = "LB"; case lesotho = "LS"; case liberia = "LR"; case libya = "LY"; case liechtenstein = "LI"; case lithuania = "LT"; case luxembourg = "LU"; case macau = "MO"; case macedonia = "MK"; case madagascar = "MG"; case malawi = "MW"; case malaysia = "MY"; case maldives = "MV"; case mali = "ML"; case malta = "MT"; case marshallIslands = "MH"; case martinique = "MQ"; case mauritania = "MR"; case mauritius = "MU"; case mayotte = "YT"; case mexico = "MX"; case micronesia = "FM"; case moldova = "MD"; case monaco = "MC"; case mongolia = "MN"; case montenegro = "ME"; case montserrat = "MS"; case morocco = "MA"; case mozambique = "MZ"; case myanmar = "MM"; case namibia = "NA"; case nauru = "NR"; case nepal = "NP"; case netherlands = "NL"; case newCaledonia = "NC"; case newZealand = "NZ"; case nicaragua = "NI"; case niger = "NE"; case nigeria = "NG"; case niue = "NU"; case norfolkIsland = "NF"; case northKorea = "KP"; case northernMarianaIslands = "MP"; case norway = "NO"; case oman = "OM"; case pakistan = "PK"; case palau = "PW"; case palestinianTerritory = "PS"; case panama = "PA"; case papuaNewGuinea = "PG"; case paraguay = "PY"; case peru = "PE"; case philippines = "PH"; case pitcairnIslands = "PN"; case poland = "PL"; case portugal = "PT"; case puertoRico = "PR"; case qatar = "QA"; case reunion = "RE"; case romania = "RO"; case russianFederation = "RU"; case rwanda = "RW"; case saintBarthelemy = "BL"; case saintHelena = "SH"; case saintKittsAndNevis = "KN"; case saintLucia = "LC"; case saintMartin = "MF"; case saintPierreAndMiquelon = "PM"; case saintVincentAndTheGrenadines = "VC"; case samoa = "WS"; case sanMarino = "SM"; case saoTomeAndPrincipe = "ST"; case saudiArabia = "SA"; case senegal = "SN"; case serbia = "RS"; case seychelles = "SC"; case sierraLeone = "SL"; case singapore = "SG"; case sintMaarten = "SX"; case slovakia = "SK"; case slovenia = "SI"; case solomonIslands = "SB"; case somalia = "SO"; case southAfrica = "ZA"; case southGeorgiaAndTheSouthSandwichIslands = "GS"; case southKorea = "KR"; case southSudan = "SS"; case spain = "ES"; case sriLanka = "LK"; case sudan = "SD"; case suriname = "SR"; case svalbardAndJanMayen = "SJ"; case swaziland = "SZ"; case sweden = "SE"; case switzerland = "CH"; case syrianArabRepublic = "SY"; case taiwan = "TW"; case tajikistan = "TJ"; case tanzania = "TZ"; case thailand = "TH"; case timorLeste = "TL"; case togo = "TG"; case tokelau = "TK"; case tonga = "TO"; case trinidadAndTobago = "TT"; case tunisia = "TN"; case turkey = "TR"; case turkmenistan = "TM"; case turksAndCaicosIslands = "TC"; case tuvalu = "TV"; case uganda = "UG"; case ukraine = "UA"; case unitedArabEmirates = "AE"; case unitedKingdom = "GB"; case unitedStates = "US"; case unitedStatesMinorOutlyingIslands = "UM"; case uruguay = "UY"; case uzbekistan = "UZ"; case vanuatu = "VU"; case venezuela = "VE"; case vietnam = "VN"; case virginIslandsBritish = "VG"; case virginIslandsUS = "VI"; case wallisAndFutuna = "WF"; case westernSahara = "EH"; case yemen = "YE"; case zambia = "ZM"; case zimbabwe = "ZW"
    }
}
extension EhSetting.BrowsingCountry {
    public var id: Int { hashValue }
    public var name: LocalizedStringResource {
        switch self {
        case .autoDetect: return .browsingCountryAutoDetect
        case .afghanistan: return .browsingCountryAfghanistan
        case .alandIslands: return .browsingCountryAlandIslands
        case .albania: return .browsingCountryAlbania
        case .algeria: return .browsingCountryAlgeria
        case .americanSamoa: return .browsingCountryAmericanSamoa
        case .andorra: return .browsingCountryAndorra
        case .angola: return .browsingCountryAngola
        case .anguilla: return .browsingCountryAnguilla
        case .antarctica: return .browsingCountryAntarctica
        case .antiguaAndBarbuda: return .browsingCountryAntiguaAndBarbuda
        case .argentina: return .browsingCountryArgentina
        case .armenia: return .browsingCountryArmenia
        case .aruba: return .browsingCountryAruba
        case .asiaPacificRegion: return .browsingCountryAsiaPacificRegion
        case .australia: return .browsingCountryAustralia
        case .austria: return .browsingCountryAustria
        case .azerbaijan: return .browsingCountryAzerbaijan
        case .bahamas: return .browsingCountryBahamas
        case .bahrain: return .browsingCountryBahrain
        case .bangladesh: return .browsingCountryBangladesh
        case .barbados: return .browsingCountryBarbados
        case .belarus: return .browsingCountryBelarus
        case .belgium: return .browsingCountryBelgium
        case .belize: return .browsingCountryBelize
        case .benin: return .browsingCountryBenin
        case .bermuda: return .browsingCountryBermuda
        case .bhutan: return .browsingCountryBhutan
        case .bolivia: return .browsingCountryBolivia
        case .bonaireSaintEustatiusAndSaba: return .browsingCountryBonaireSaintEustatiusAndSaba
        case .bosniaAndHerzegovina: return .browsingCountryBosniaAndHerzegovina
        case .botswana: return .browsingCountryBotswana
        case .bouvetIsland: return .browsingCountryBouvetIsland
        case .brazil: return .browsingCountryBrazil
        case .britishIndianOceanTerritory: return .browsingCountryBritishIndianOceanTerritory
        case .bruneiDarussalam: return .browsingCountryBruneiDarussalam
        case .bulgaria: return .browsingCountryBulgaria
        case .burkinaFaso: return .browsingCountryBurkinaFaso
        case .burundi: return .browsingCountryBurundi
        case .cambodia: return .browsingCountryCambodia
        case .cameroon: return .browsingCountryCameroon
        case .canada: return .browsingCountryCanada
        case .capeVerde: return .browsingCountryCapeVerde
        case .caymanIslands: return .browsingCountryCaymanIslands
        case .centralAfricanRepublic: return .browsingCountryCentralAfricanRepublic
        case .chad: return .browsingCountryChad
        case .chile: return .browsingCountryChile
        case .china: return .browsingCountryChina
        case .christmasIsland: return .browsingCountryChristmasIsland
        case .cocosIslands: return .browsingCountryCocosIslands
        case .colombia: return .browsingCountryColombia
        case .comoros: return .browsingCountryComoros
        case .congo: return .browsingCountryCongo
        case .theDemocraticRepublicOfTheCongo: return .browsingCountryTheDemocraticRepublicOfTheCongo
        case .cookIslands: return .browsingCountryCookIslands
        case .costaRica: return .browsingCountryCostaRica
        case .coteDIvoire: return .browsingCountryCoteDIvoire
        case .croatia: return .browsingCountryCroatia
        case .cuba: return .browsingCountryCuba
        case .curacao: return .browsingCountryCuracao
        case .cyprus: return .browsingCountryCyprus
        case .czechRepublic: return .browsingCountryCzechRepublic
        case .denmark: return .browsingCountryDenmark
        case .djibouti: return .browsingCountryDjibouti
        case .dominica: return .browsingCountryDominica
        case .dominicanRepublic: return .browsingCountryDominicanRepublic
        case .ecuador: return .browsingCountryEcuador
        case .egypt: return .browsingCountryEgypt
        case .elSalvador: return .browsingCountryElSalvador
        case .equatorialGuinea: return .browsingCountryEquatorialGuinea
        case .eritrea: return .browsingCountryEritrea
        case .estonia: return .browsingCountryEstonia
        case .ethiopia: return .browsingCountryEthiopia
        case .europe: return .browsingCountryEurope
        case .falklandIslands: return .browsingCountryFalklandIslands
        case .faroeIslands: return .browsingCountryFaroeIslands
        case .fiji: return .browsingCountryFiji
        case .finland: return .browsingCountryFinland
        case .france: return .browsingCountryFrance
        case .frenchGuiana: return .browsingCountryFrenchGuiana
        case .frenchPolynesia: return .browsingCountryFrenchPolynesia
        case .frenchSouthernTerritories: return .browsingCountryFrenchSouthernTerritories
        case .gabon: return .browsingCountryGabon
        case .gambia: return .browsingCountryGambia
        case .georgia: return .browsingCountryGeorgia
        case .germany: return .browsingCountryGermany
        case .ghana: return .browsingCountryGhana
        case .gibraltar: return .browsingCountryGibraltar
        case .greece: return .browsingCountryGreece
        case .greenland: return .browsingCountryGreenland
        case .grenada: return .browsingCountryGrenada
        case .guadeloupe: return .browsingCountryGuadeloupe
        case .guam: return .browsingCountryGuam
        case .guatemala: return .browsingCountryGuatemala
        case .guernsey: return .browsingCountryGuernsey
        case .guinea: return .browsingCountryGuinea
        case .guineaBissau: return .browsingCountryGuineaBissau
        case .guyana: return .browsingCountryGuyana
        case .haiti: return .browsingCountryHaiti
        case .heardIslandAndMcDonaldIslands: return .browsingCountryHeardIslandAndMcDonaldIslands
        case .vaticanCityState: return .browsingCountryVaticanCityState
        case .honduras: return .browsingCountryHonduras
        case .hongKong: return .browsingCountryHongKong
        case .hungary: return .browsingCountryHungary
        case .iceland: return .browsingCountryIceland
        case .india: return .browsingCountryIndia
        case .indonesia: return .browsingCountryIndonesia
        case .iran: return .browsingCountryIran
        case .iraq: return .browsingCountryIraq
        case .ireland: return .browsingCountryIreland
        case .isleOfMan: return .browsingCountryIsleOfMan
        case .israel: return .browsingCountryIsrael
        case .italy: return .browsingCountryItaly
        case .jamaica: return .browsingCountryJamaica
        case .japan: return .browsingCountryJapan
        case .jersey: return .browsingCountryJersey
        case .jordan: return .browsingCountryJordan
        case .kazakhstan: return .browsingCountryKazakhstan
        case .kenya: return .browsingCountryKenya
        case .kiribati: return .browsingCountryKiribati
        case .kuwait: return .browsingCountryKuwait
        case .kyrgyzstan: return .browsingCountryKyrgyzstan
        case .laoPeoplesDemocraticRepublic: return .browsingCountryLaoPeoplesDemocraticRepublic
        case .latvia: return .browsingCountryLatvia
        case .lebanon: return .browsingCountryLebanon
        case .lesotho: return .browsingCountryLesotho
        case .liberia: return .browsingCountryLiberia
        case .libya: return .browsingCountryLibya
        case .liechtenstein: return .browsingCountryLiechtenstein
        case .lithuania: return .browsingCountryLithuania
        case .luxembourg: return .browsingCountryLuxembourg
        case .macau: return .browsingCountryMacau
        case .macedonia: return .browsingCountryMacedonia
        case .madagascar: return .browsingCountryMadagascar
        case .malawi: return .browsingCountryMalawi
        case .malaysia: return .browsingCountryMalaysia
        case .maldives: return .browsingCountryMaldives
        case .mali: return .browsingCountryMali
        case .malta: return .browsingCountryMalta
        case .marshallIslands: return .browsingCountryMarshallIslands
        case .martinique: return .browsingCountryMartinique
        case .mauritania: return .browsingCountryMauritania
        case .mauritius: return .browsingCountryMauritius
        case .mayotte: return .browsingCountryMayotte
        case .mexico: return .browsingCountryMexico
        case .micronesia: return .browsingCountryMicronesia
        case .moldova: return .browsingCountryMoldova
        case .monaco: return .browsingCountryMonaco
        case .mongolia: return .browsingCountryMongolia
        case .montenegro: return .browsingCountryMontenegro
        case .montserrat: return .browsingCountryMontserrat
        case .morocco: return .browsingCountryMorocco
        case .mozambique: return .browsingCountryMozambique
        case .myanmar: return .browsingCountryMyanmar
        case .namibia: return .browsingCountryNamibia
        case .nauru: return .browsingCountryNauru
        case .nepal: return .browsingCountryNepal
        case .netherlands: return .browsingCountryNetherlands
        case .newCaledonia: return .browsingCountryNewCaledonia
        case .newZealand: return .browsingCountryNewZealand
        case .nicaragua: return .browsingCountryNicaragua
        case .niger: return .browsingCountryNiger
        case .nigeria: return .browsingCountryNigeria
        case .niue: return .browsingCountryNiue
        case .norfolkIsland: return .browsingCountryNorfolkIsland
        case .northKorea: return .browsingCountryNorthKorea
        case .northernMarianaIslands: return .browsingCountryNorthernMarianaIslands
        case .norway: return .browsingCountryNorway
        case .oman: return .browsingCountryOman
        case .pakistan: return .browsingCountryPakistan
        case .palau: return .browsingCountryPalau
        case .palestinianTerritory: return .browsingCountryPalestinianTerritory
        case .panama: return .browsingCountryPanama
        case .papuaNewGuinea: return .browsingCountryPapuaNewGuinea
        case .paraguay: return .browsingCountryParaguay
        case .peru: return .browsingCountryPeru
        case .philippines: return .browsingCountryPhilippines
        case .pitcairnIslands: return .browsingCountryPitcairnIslands
        case .poland: return .browsingCountryPoland
        case .portugal: return .browsingCountryPortugal
        case .puertoRico: return .browsingCountryPuertoRico
        case .qatar: return .browsingCountryQatar
        case .reunion: return .browsingCountryReunion
        case .romania: return .browsingCountryRomania
        case .russianFederation: return .browsingCountryRussianFederation
        case .rwanda: return .browsingCountryRwanda
        case .saintBarthelemy: return .browsingCountrySaintBarthelemy
        case .saintHelena: return .browsingCountrySaintHelena
        case .saintKittsAndNevis: return .browsingCountrySaintKittsAndNevis
        case .saintLucia: return .browsingCountrySaintLucia
        case .saintMartin: return .browsingCountrySaintMartin
        case .saintPierreAndMiquelon: return .browsingCountrySaintPierreAndMiquelon
        case .saintVincentAndTheGrenadines: return .browsingCountrySaintVincentAndTheGrenadines
        case .samoa: return .browsingCountrySamoa
        case .sanMarino: return .browsingCountrySanMarino
        case .saoTomeAndPrincipe: return .browsingCountrySaoTomeAndPrincipe
        case .saudiArabia: return .browsingCountrySaudiArabia
        case .senegal: return .browsingCountrySenegal
        case .serbia: return .browsingCountrySerbia
        case .seychelles: return .browsingCountrySeychelles
        case .sierraLeone: return .browsingCountrySierraLeone
        case .singapore: return .browsingCountrySingapore
        case .sintMaarten: return .browsingCountrySintMaarten
        case .slovakia: return .browsingCountrySlovakia
        case .slovenia: return .browsingCountrySlovenia
        case .solomonIslands: return .browsingCountrySolomonIslands
        case .somalia: return .browsingCountrySomalia
        case .southAfrica: return .browsingCountrySouthAfrica
        case .southGeorgiaAndTheSouthSandwichIslands: return .browsingCountrySouthGeorgiaAndTheSouthSandwichIslands
        case .southKorea: return .browsingCountrySouthKorea
        case .southSudan: return .browsingCountrySouthSudan
        case .spain: return .browsingCountrySpain
        case .sriLanka: return .browsingCountrySriLanka
        case .sudan: return .browsingCountrySudan
        case .suriname: return .browsingCountrySuriname
        case .svalbardAndJanMayen: return .browsingCountrySvalbardAndJanMayen
        case .swaziland: return .browsingCountrySwaziland
        case .sweden: return .browsingCountrySweden
        case .switzerland: return .browsingCountrySwitzerland
        case .syrianArabRepublic: return .browsingCountrySyrianArabRepublic
        case .taiwan: return .browsingCountryTaiwan
        case .tajikistan: return .browsingCountryTajikistan
        case .tanzania: return .browsingCountryTanzania
        case .thailand: return .browsingCountryThailand
        case .timorLeste: return .browsingCountryTimorLeste
        case .togo: return .browsingCountryTogo
        case .tokelau: return .browsingCountryTokelau
        case .tonga: return .browsingCountryTonga
        case .trinidadAndTobago: return .browsingCountryTrinidadAndTobago
        case .tunisia: return .browsingCountryTunisia
        case .turkey: return .browsingCountryTurkey
        case .turkmenistan: return .browsingCountryTurkmenistan
        case .turksAndCaicosIslands: return .browsingCountryTurksAndCaicosIslands
        case .tuvalu: return .browsingCountryTuvalu
        case .uganda: return .browsingCountryUganda
        case .ukraine: return .browsingCountryUkraine
        case .unitedArabEmirates: return .browsingCountryUnitedArabEmirates
        case .unitedKingdom: return .browsingCountryUnitedKingdom
        case .unitedStates: return .browsingCountryUnitedStates
        case .unitedStatesMinorOutlyingIslands: return .browsingCountryUnitedStatesMinorOutlyingIslands
        case .uruguay: return .browsingCountryUruguay
        case .uzbekistan: return .browsingCountryUzbekistan
        case .vanuatu: return .browsingCountryVanuatu
        case .venezuela: return .browsingCountryVenezuela
        case .vietnam: return .browsingCountryVietnam
        case .virginIslandsBritish: return .browsingCountryVirginIslandsBritish
        case .virginIslandsUS: return .browsingCountryVirginIslandsUs
        case .wallisAndFutuna: return .browsingCountryWallisAndFutuna
        case .westernSahara: return .browsingCountryWesternSahara
        case .yemen: return .browsingCountryYemen
        case .zambia: return .browsingCountryZambia
        case .zimbabwe: return .browsingCountryZimbabwe
        }
    }
}
// swiftlint:enable line_length
