import Foundation
import Resources

// reason: the exhaustive ISO country list is kept dense, one case per line
// swiftlint:disable line_length
extension EhSetting {
    public enum BrowsingCountry: String, CaseIterable, Identifiable, Equatable, Sendable {
        case autoDetect = "-"; case afghanistan = "AF"; case alandIslands = "AX"; case albania = "AL"; case algeria = "DZ"; case americanSamoa = "AS"; case andorra = "AD"; case angola = "AO"; case anguilla = "AI"; case antarctica = "AQ"; case antiguaAndBarbuda = "AG"; case argentina = "AR"; case armenia = "AM"; case aruba = "AW"; case asiaPacificRegion = "AP"; case australia = "AU"; case austria = "AT"; case azerbaijan = "AZ"; case bahamas = "BS"; case bahrain = "BH"; case bangladesh = "BD"; case barbados = "BB"; case belarus = "BY"; case belgium = "BE"; case belize = "BZ"; case benin = "BJ"; case bermuda = "BM"; case bhutan = "BT"; case bolivia = "BO"; case bonaireSaintEustatiusAndSaba = "BQ"; case bosniaAndHerzegovina = "BA"; case botswana = "BW"; case bouvetIsland = "BV"; case brazil = "BR"; case britishIndianOceanTerritory = "IO"; case bruneiDarussalam = "BN"; case bulgaria = "BG"; case burkinaFaso = "BF"; case burundi = "BI"; case cambodia = "KH"; case cameroon = "CM"; case canada = "CA"; case capeVerde = "CV"; case caymanIslands = "KY"; case centralAfricanRepublic = "CF"; case chad = "TD"; case chile = "CL"; case china = "CN"; case christmasIsland = "CX"; case cocosIslands = "CC"; case colombia = "CO"; case comoros = "KM"; case congo = "CG"; case theDemocraticRepublicOfTheCongo = "CD"; case cookIslands = "CK"; case costaRica = "CR"; case coteDIvoire = "CI"; case croatia = "HR"; case cuba = "CU"; case curacao = "CW"; case cyprus = "CY"; case czechRepublic = "CZ"; case denmark = "DK"; case djibouti = "DJ"; case dominica = "DM"; case dominicanRepublic = "DO"; case ecuador = "EC"; case egypt = "EG"; case elSalvador = "SV"; case equatorialGuinea = "GQ"; case eritrea = "ER"; case estonia = "EE"; case ethiopia = "ET"; case europe = "EU"; case falklandIslands = "FK"; case faroeIslands = "FO"; case fiji = "FJ"; case finland = "FI"; case france = "FR"; case frenchGuiana = "GF"; case frenchPolynesia = "PF"; case frenchSouthernTerritories = "TF"; case gabon = "GA"; case gambia = "GM"; case georgia = "GE"; case germany = "DE"; case ghana = "GH"; case gibraltar = "GI"; case greece = "GR"; case greenland = "GL"; case grenada = "GD"; case guadeloupe = "GP"; case guam = "GU"; case guatemala = "GT"; case guernsey = "GG"; case guinea = "GN"; case guineaBissau = "GW"; case guyana = "GY"; case haiti = "HT"; case heardIslandAndMcDonaldIslands = "HM"; case vaticanCityState = "VA"; case honduras = "HN"; case hongKong = "HK"; case hungary = "HU"; case iceland = "IS"; case india = "IN"; case indonesia = "ID"; case iran = "IR"; case iraq = "IQ"; case ireland = "IE"; case isleOfMan = "IM"; case israel = "IL"; case italy = "IT"; case jamaica = "JM"; case japan = "JP"; case jersey = "JE"; case jordan = "JO"; case kazakhstan = "KZ"; case kenya = "KE"; case kiribati = "KI"; case kuwait = "KW"; case kyrgyzstan = "KG"; case laoPeoplesDemocraticRepublic = "LA"; case latvia = "LV"; case lebanon = "LB"; case lesotho = "LS"; case liberia = "LR"; case libya = "LY"; case liechtenstein = "LI"; case lithuania = "LT"; case luxembourg = "LU"; case macau = "MO"; case macedonia = "MK"; case madagascar = "MG"; case malawi = "MW"; case malaysia = "MY"; case maldives = "MV"; case mali = "ML"; case malta = "MT"; case marshallIslands = "MH"; case martinique = "MQ"; case mauritania = "MR"; case mauritius = "MU"; case mayotte = "YT"; case mexico = "MX"; case micronesia = "FM"; case moldova = "MD"; case monaco = "MC"; case mongolia = "MN"; case montenegro = "ME"; case montserrat = "MS"; case morocco = "MA"; case mozambique = "MZ"; case myanmar = "MM"; case namibia = "NA"; case nauru = "NR"; case nepal = "NP"; case netherlands = "NL"; case newCaledonia = "NC"; case newZealand = "NZ"; case nicaragua = "NI"; case niger = "NE"; case nigeria = "NG"; case niue = "NU"; case norfolkIsland = "NF"; case northKorea = "KP"; case northernMarianaIslands = "MP"; case norway = "NO"; case oman = "OM"; case pakistan = "PK"; case palau = "PW"; case palestinianTerritory = "PS"; case panama = "PA"; case papuaNewGuinea = "PG"; case paraguay = "PY"; case peru = "PE"; case philippines = "PH"; case pitcairnIslands = "PN"; case poland = "PL"; case portugal = "PT"; case puertoRico = "PR"; case qatar = "QA"; case reunion = "RE"; case romania = "RO"; case russianFederation = "RU"; case rwanda = "RW"; case saintBarthelemy = "BL"; case saintHelena = "SH"; case saintKittsAndNevis = "KN"; case saintLucia = "LC"; case saintMartin = "MF"; case saintPierreAndMiquelon = "PM"; case saintVincentAndTheGrenadines = "VC"; case samoa = "WS"; case sanMarino = "SM"; case saoTomeAndPrincipe = "ST"; case saudiArabia = "SA"; case senegal = "SN"; case serbia = "RS"; case seychelles = "SC"; case sierraLeone = "SL"; case singapore = "SG"; case sintMaarten = "SX"; case slovakia = "SK"; case slovenia = "SI"; case solomonIslands = "SB"; case somalia = "SO"; case southAfrica = "ZA"; case southGeorgiaAndTheSouthSandwichIslands = "GS"; case southKorea = "KR"; case southSudan = "SS"; case spain = "ES"; case sriLanka = "LK"; case sudan = "SD"; case suriname = "SR"; case svalbardAndJanMayen = "SJ"; case swaziland = "SZ"; case sweden = "SE"; case switzerland = "CH"; case syrianArabRepublic = "SY"; case taiwan = "TW"; case tajikistan = "TJ"; case tanzania = "TZ"; case thailand = "TH"; case timorLeste = "TL"; case togo = "TG"; case tokelau = "TK"; case tonga = "TO"; case trinidadAndTobago = "TT"; case tunisia = "TN"; case turkey = "TR"; case turkmenistan = "TM"; case turksAndCaicosIslands = "TC"; case tuvalu = "TV"; case uganda = "UG"; case ukraine = "UA"; case unitedArabEmirates = "AE"; case unitedKingdom = "GB"; case unitedStates = "US"; case unitedStatesMinorOutlyingIslands = "UM"; case uruguay = "UY"; case uzbekistan = "UZ"; case vanuatu = "VU"; case venezuela = "VE"; case vietnam = "VN"; case virginIslandsBritish = "VG"; case virginIslandsUS = "VI"; case wallisAndFutuna = "WF"; case westernSahara = "EH"; case yemen = "YE"; case zambia = "ZM"; case zimbabwe = "ZW"
    }
}
extension EhSetting.BrowsingCountry {
    public var id: Int { hashValue }
    public var name: String {
        switch self {
        case .autoDetect: return L10n.Localizable.BrowsingCountry.autoDetect
        case .afghanistan: return L10n.Localizable.BrowsingCountry.afghanistan
        case .alandIslands: return L10n.Localizable.BrowsingCountry.alandIslands
        case .albania: return L10n.Localizable.BrowsingCountry.albania
        case .algeria: return L10n.Localizable.BrowsingCountry.algeria
        case .americanSamoa: return L10n.Localizable.BrowsingCountry.americanSamoa
        case .andorra: return L10n.Localizable.BrowsingCountry.andorra
        case .angola: return L10n.Localizable.BrowsingCountry.angola
        case .anguilla: return L10n.Localizable.BrowsingCountry.anguilla
        case .antarctica: return L10n.Localizable.BrowsingCountry.antarctica
        case .antiguaAndBarbuda: return L10n.Localizable.BrowsingCountry.antiguaAndBarbuda
        case .argentina: return L10n.Localizable.BrowsingCountry.argentina
        case .armenia: return L10n.Localizable.BrowsingCountry.armenia
        case .aruba: return L10n.Localizable.BrowsingCountry.aruba
        case .asiaPacificRegion: return L10n.Localizable.BrowsingCountry.asiaPacificRegion
        case .australia: return L10n.Localizable.BrowsingCountry.australia
        case .austria: return L10n.Localizable.BrowsingCountry.austria
        case .azerbaijan: return L10n.Localizable.BrowsingCountry.azerbaijan
        case .bahamas: return L10n.Localizable.BrowsingCountry.bahamas
        case .bahrain: return L10n.Localizable.BrowsingCountry.bahrain
        case .bangladesh: return L10n.Localizable.BrowsingCountry.bangladesh
        case .barbados: return L10n.Localizable.BrowsingCountry.barbados
        case .belarus: return L10n.Localizable.BrowsingCountry.belarus
        case .belgium: return L10n.Localizable.BrowsingCountry.belgium
        case .belize: return L10n.Localizable.BrowsingCountry.belize
        case .benin: return L10n.Localizable.BrowsingCountry.benin
        case .bermuda: return L10n.Localizable.BrowsingCountry.bermuda
        case .bhutan: return L10n.Localizable.BrowsingCountry.bhutan
        case .bolivia: return L10n.Localizable.BrowsingCountry.bolivia
        case .bonaireSaintEustatiusAndSaba: return L10n.Localizable.BrowsingCountry.bonaireSaintEustatiusAndSaba
        case .bosniaAndHerzegovina: return L10n.Localizable.BrowsingCountry.bosniaAndHerzegovina
        case .botswana: return L10n.Localizable.BrowsingCountry.botswana
        case .bouvetIsland: return L10n.Localizable.BrowsingCountry.bouvetIsland
        case .brazil: return L10n.Localizable.BrowsingCountry.brazil
        case .britishIndianOceanTerritory: return L10n.Localizable.BrowsingCountry.britishIndianOceanTerritory
        case .bruneiDarussalam: return L10n.Localizable.BrowsingCountry.bruneiDarussalam
        case .bulgaria: return L10n.Localizable.BrowsingCountry.bulgaria
        case .burkinaFaso: return L10n.Localizable.BrowsingCountry.burkinaFaso
        case .burundi: return L10n.Localizable.BrowsingCountry.burundi
        case .cambodia: return L10n.Localizable.BrowsingCountry.cambodia
        case .cameroon: return L10n.Localizable.BrowsingCountry.cameroon
        case .canada: return L10n.Localizable.BrowsingCountry.canada
        case .capeVerde: return L10n.Localizable.BrowsingCountry.capeVerde
        case .caymanIslands: return L10n.Localizable.BrowsingCountry.caymanIslands
        case .centralAfricanRepublic: return L10n.Localizable.BrowsingCountry.centralAfricanRepublic
        case .chad: return L10n.Localizable.BrowsingCountry.chad
        case .chile: return L10n.Localizable.BrowsingCountry.chile
        case .china: return L10n.Localizable.BrowsingCountry.china
        case .christmasIsland: return L10n.Localizable.BrowsingCountry.christmasIsland
        case .cocosIslands: return L10n.Localizable.BrowsingCountry.cocosIslands
        case .colombia: return L10n.Localizable.BrowsingCountry.colombia
        case .comoros: return L10n.Localizable.BrowsingCountry.comoros
        case .congo: return L10n.Localizable.BrowsingCountry.congo
        case .theDemocraticRepublicOfTheCongo: return L10n.Localizable.BrowsingCountry.theDemocraticRepublicOfTheCongo
        case .cookIslands: return L10n.Localizable.BrowsingCountry.cookIslands
        case .costaRica: return L10n.Localizable.BrowsingCountry.costaRica
        case .coteDIvoire: return L10n.Localizable.BrowsingCountry.coteDIvoire
        case .croatia: return L10n.Localizable.BrowsingCountry.croatia
        case .cuba: return L10n.Localizable.BrowsingCountry.cuba
        case .curacao: return L10n.Localizable.BrowsingCountry.curacao
        case .cyprus: return L10n.Localizable.BrowsingCountry.cyprus
        case .czechRepublic: return L10n.Localizable.BrowsingCountry.czechRepublic
        case .denmark: return L10n.Localizable.BrowsingCountry.denmark
        case .djibouti: return L10n.Localizable.BrowsingCountry.djibouti
        case .dominica: return L10n.Localizable.BrowsingCountry.dominica
        case .dominicanRepublic: return L10n.Localizable.BrowsingCountry.dominicanRepublic
        case .ecuador: return L10n.Localizable.BrowsingCountry.ecuador
        case .egypt: return L10n.Localizable.BrowsingCountry.egypt
        case .elSalvador: return L10n.Localizable.BrowsingCountry.elSalvador
        case .equatorialGuinea: return L10n.Localizable.BrowsingCountry.equatorialGuinea
        case .eritrea: return L10n.Localizable.BrowsingCountry.eritrea
        case .estonia: return L10n.Localizable.BrowsingCountry.estonia
        case .ethiopia: return L10n.Localizable.BrowsingCountry.ethiopia
        case .europe: return L10n.Localizable.BrowsingCountry.europe
        case .falklandIslands: return L10n.Localizable.BrowsingCountry.falklandIslands
        case .faroeIslands: return L10n.Localizable.BrowsingCountry.faroeIslands
        case .fiji: return L10n.Localizable.BrowsingCountry.fiji
        case .finland: return L10n.Localizable.BrowsingCountry.finland
        case .france: return L10n.Localizable.BrowsingCountry.france
        case .frenchGuiana: return L10n.Localizable.BrowsingCountry.frenchGuiana
        case .frenchPolynesia: return L10n.Localizable.BrowsingCountry.frenchPolynesia
        case .frenchSouthernTerritories: return L10n.Localizable.BrowsingCountry.frenchSouthernTerritories
        case .gabon: return L10n.Localizable.BrowsingCountry.gabon
        case .gambia: return L10n.Localizable.BrowsingCountry.gambia
        case .georgia: return L10n.Localizable.BrowsingCountry.georgia
        case .germany: return L10n.Localizable.BrowsingCountry.germany
        case .ghana: return L10n.Localizable.BrowsingCountry.ghana
        case .gibraltar: return L10n.Localizable.BrowsingCountry.gibraltar
        case .greece: return L10n.Localizable.BrowsingCountry.greece
        case .greenland: return L10n.Localizable.BrowsingCountry.greenland
        case .grenada: return L10n.Localizable.BrowsingCountry.grenada
        case .guadeloupe: return L10n.Localizable.BrowsingCountry.guadeloupe
        case .guam: return L10n.Localizable.BrowsingCountry.guam
        case .guatemala: return L10n.Localizable.BrowsingCountry.guatemala
        case .guernsey: return L10n.Localizable.BrowsingCountry.guernsey
        case .guinea: return L10n.Localizable.BrowsingCountry.guinea
        case .guineaBissau: return L10n.Localizable.BrowsingCountry.guineaBissau
        case .guyana: return L10n.Localizable.BrowsingCountry.guyana
        case .haiti: return L10n.Localizable.BrowsingCountry.haiti
        case .heardIslandAndMcDonaldIslands: return L10n.Localizable.BrowsingCountry.heardIslandAndMcDonaldIslands
        case .vaticanCityState: return L10n.Localizable.BrowsingCountry.vaticanCityState
        case .honduras: return L10n.Localizable.BrowsingCountry.honduras
        case .hongKong: return L10n.Localizable.BrowsingCountry.hongKong
        case .hungary: return L10n.Localizable.BrowsingCountry.hungary
        case .iceland: return L10n.Localizable.BrowsingCountry.iceland
        case .india: return L10n.Localizable.BrowsingCountry.india
        case .indonesia: return L10n.Localizable.BrowsingCountry.indonesia
        case .iran: return L10n.Localizable.BrowsingCountry.iran
        case .iraq: return L10n.Localizable.BrowsingCountry.iraq
        case .ireland: return L10n.Localizable.BrowsingCountry.ireland
        case .isleOfMan: return L10n.Localizable.BrowsingCountry.isleOfMan
        case .israel: return L10n.Localizable.BrowsingCountry.israel
        case .italy: return L10n.Localizable.BrowsingCountry.italy
        case .jamaica: return L10n.Localizable.BrowsingCountry.jamaica
        case .japan: return L10n.Localizable.BrowsingCountry.japan
        case .jersey: return L10n.Localizable.BrowsingCountry.jersey
        case .jordan: return L10n.Localizable.BrowsingCountry.jordan
        case .kazakhstan: return L10n.Localizable.BrowsingCountry.kazakhstan
        case .kenya: return L10n.Localizable.BrowsingCountry.kenya
        case .kiribati: return L10n.Localizable.BrowsingCountry.kiribati
        case .kuwait: return L10n.Localizable.BrowsingCountry.kuwait
        case .kyrgyzstan: return L10n.Localizable.BrowsingCountry.kyrgyzstan
        case .laoPeoplesDemocraticRepublic: return L10n.Localizable.BrowsingCountry.laoPeoplesDemocraticRepublic
        case .latvia: return L10n.Localizable.BrowsingCountry.latvia
        case .lebanon: return L10n.Localizable.BrowsingCountry.lebanon
        case .lesotho: return L10n.Localizable.BrowsingCountry.lesotho
        case .liberia: return L10n.Localizable.BrowsingCountry.liberia
        case .libya: return L10n.Localizable.BrowsingCountry.libya
        case .liechtenstein: return L10n.Localizable.BrowsingCountry.liechtenstein
        case .lithuania: return L10n.Localizable.BrowsingCountry.lithuania
        case .luxembourg: return L10n.Localizable.BrowsingCountry.luxembourg
        case .macau: return L10n.Localizable.BrowsingCountry.macau
        case .macedonia: return L10n.Localizable.BrowsingCountry.macedonia
        case .madagascar: return L10n.Localizable.BrowsingCountry.madagascar
        case .malawi: return L10n.Localizable.BrowsingCountry.malawi
        case .malaysia: return L10n.Localizable.BrowsingCountry.malaysia
        case .maldives: return L10n.Localizable.BrowsingCountry.maldives
        case .mali: return L10n.Localizable.BrowsingCountry.mali
        case .malta: return L10n.Localizable.BrowsingCountry.malta
        case .marshallIslands: return L10n.Localizable.BrowsingCountry.marshallIslands
        case .martinique: return L10n.Localizable.BrowsingCountry.martinique
        case .mauritania: return L10n.Localizable.BrowsingCountry.mauritania
        case .mauritius: return L10n.Localizable.BrowsingCountry.mauritius
        case .mayotte: return L10n.Localizable.BrowsingCountry.mayotte
        case .mexico: return L10n.Localizable.BrowsingCountry.mexico
        case .micronesia: return L10n.Localizable.BrowsingCountry.micronesia
        case .moldova: return L10n.Localizable.BrowsingCountry.moldova
        case .monaco: return L10n.Localizable.BrowsingCountry.monaco
        case .mongolia: return L10n.Localizable.BrowsingCountry.mongolia
        case .montenegro: return L10n.Localizable.BrowsingCountry.montenegro
        case .montserrat: return L10n.Localizable.BrowsingCountry.montserrat
        case .morocco: return L10n.Localizable.BrowsingCountry.morocco
        case .mozambique: return L10n.Localizable.BrowsingCountry.mozambique
        case .myanmar: return L10n.Localizable.BrowsingCountry.myanmar
        case .namibia: return L10n.Localizable.BrowsingCountry.namibia
        case .nauru: return L10n.Localizable.BrowsingCountry.nauru
        case .nepal: return L10n.Localizable.BrowsingCountry.nepal
        case .netherlands: return L10n.Localizable.BrowsingCountry.netherlands
        case .newCaledonia: return L10n.Localizable.BrowsingCountry.newCaledonia
        case .newZealand: return L10n.Localizable.BrowsingCountry.newZealand
        case .nicaragua: return L10n.Localizable.BrowsingCountry.nicaragua
        case .niger: return L10n.Localizable.BrowsingCountry.niger
        case .nigeria: return L10n.Localizable.BrowsingCountry.nigeria
        case .niue: return L10n.Localizable.BrowsingCountry.niue
        case .norfolkIsland: return L10n.Localizable.BrowsingCountry.norfolkIsland
        case .northKorea: return L10n.Localizable.BrowsingCountry.northKorea
        case .northernMarianaIslands: return L10n.Localizable.BrowsingCountry.northernMarianaIslands
        case .norway: return L10n.Localizable.BrowsingCountry.norway
        case .oman: return L10n.Localizable.BrowsingCountry.oman
        case .pakistan: return L10n.Localizable.BrowsingCountry.pakistan
        case .palau: return L10n.Localizable.BrowsingCountry.palau
        case .palestinianTerritory: return L10n.Localizable.BrowsingCountry.palestinianTerritory
        case .panama: return L10n.Localizable.BrowsingCountry.panama
        case .papuaNewGuinea: return L10n.Localizable.BrowsingCountry.papuaNewGuinea
        case .paraguay: return L10n.Localizable.BrowsingCountry.paraguay
        case .peru: return L10n.Localizable.BrowsingCountry.peru
        case .philippines: return L10n.Localizable.BrowsingCountry.philippines
        case .pitcairnIslands: return L10n.Localizable.BrowsingCountry.pitcairnIslands
        case .poland: return L10n.Localizable.BrowsingCountry.poland
        case .portugal: return L10n.Localizable.BrowsingCountry.portugal
        case .puertoRico: return L10n.Localizable.BrowsingCountry.puertoRico
        case .qatar: return L10n.Localizable.BrowsingCountry.qatar
        case .reunion: return L10n.Localizable.BrowsingCountry.reunion
        case .romania: return L10n.Localizable.BrowsingCountry.romania
        case .russianFederation: return L10n.Localizable.BrowsingCountry.russianFederation
        case .rwanda: return L10n.Localizable.BrowsingCountry.rwanda
        case .saintBarthelemy: return L10n.Localizable.BrowsingCountry.saintBarthelemy
        case .saintHelena: return L10n.Localizable.BrowsingCountry.saintHelena
        case .saintKittsAndNevis: return L10n.Localizable.BrowsingCountry.saintKittsAndNevis
        case .saintLucia: return L10n.Localizable.BrowsingCountry.saintLucia
        case .saintMartin: return L10n.Localizable.BrowsingCountry.saintMartin
        case .saintPierreAndMiquelon: return L10n.Localizable.BrowsingCountry.saintPierreAndMiquelon
        case .saintVincentAndTheGrenadines: return L10n.Localizable.BrowsingCountry.saintVincentAndTheGrenadines
        case .samoa: return L10n.Localizable.BrowsingCountry.samoa
        case .sanMarino: return L10n.Localizable.BrowsingCountry.sanMarino
        case .saoTomeAndPrincipe: return L10n.Localizable.BrowsingCountry.saoTomeAndPrincipe
        case .saudiArabia: return L10n.Localizable.BrowsingCountry.saudiArabia
        case .senegal: return L10n.Localizable.BrowsingCountry.senegal
        case .serbia: return L10n.Localizable.BrowsingCountry.serbia
        case .seychelles: return L10n.Localizable.BrowsingCountry.seychelles
        case .sierraLeone: return L10n.Localizable.BrowsingCountry.sierraLeone
        case .singapore: return L10n.Localizable.BrowsingCountry.singapore
        case .sintMaarten: return L10n.Localizable.BrowsingCountry.sintMaarten
        case .slovakia: return L10n.Localizable.BrowsingCountry.slovakia
        case .slovenia: return L10n.Localizable.BrowsingCountry.slovenia
        case .solomonIslands: return L10n.Localizable.BrowsingCountry.solomonIslands
        case .somalia: return L10n.Localizable.BrowsingCountry.somalia
        case .southAfrica: return L10n.Localizable.BrowsingCountry.southAfrica
        case .southGeorgiaAndTheSouthSandwichIslands: return L10n.Localizable.BrowsingCountry.southGeorgiaAndTheSouthSandwichIslands
        case .southKorea: return L10n.Localizable.BrowsingCountry.southKorea
        case .southSudan: return L10n.Localizable.BrowsingCountry.southSudan
        case .spain: return L10n.Localizable.BrowsingCountry.spain
        case .sriLanka: return L10n.Localizable.BrowsingCountry.sriLanka
        case .sudan: return L10n.Localizable.BrowsingCountry.sudan
        case .suriname: return L10n.Localizable.BrowsingCountry.suriname
        case .svalbardAndJanMayen: return L10n.Localizable.BrowsingCountry.svalbardAndJanMayen
        case .swaziland: return L10n.Localizable.BrowsingCountry.swaziland
        case .sweden: return L10n.Localizable.BrowsingCountry.sweden
        case .switzerland: return L10n.Localizable.BrowsingCountry.switzerland
        case .syrianArabRepublic: return L10n.Localizable.BrowsingCountry.syrianArabRepublic
        case .taiwan: return L10n.Localizable.BrowsingCountry.taiwan
        case .tajikistan: return L10n.Localizable.BrowsingCountry.tajikistan
        case .tanzania: return L10n.Localizable.BrowsingCountry.tanzania
        case .thailand: return L10n.Localizable.BrowsingCountry.thailand
        case .timorLeste: return L10n.Localizable.BrowsingCountry.timorLeste
        case .togo: return L10n.Localizable.BrowsingCountry.togo
        case .tokelau: return L10n.Localizable.BrowsingCountry.tokelau
        case .tonga: return L10n.Localizable.BrowsingCountry.tonga
        case .trinidadAndTobago: return L10n.Localizable.BrowsingCountry.trinidadAndTobago
        case .tunisia: return L10n.Localizable.BrowsingCountry.tunisia
        case .turkey: return L10n.Localizable.BrowsingCountry.turkey
        case .turkmenistan: return L10n.Localizable.BrowsingCountry.turkmenistan
        case .turksAndCaicosIslands: return L10n.Localizable.BrowsingCountry.turksAndCaicosIslands
        case .tuvalu: return L10n.Localizable.BrowsingCountry.tuvalu
        case .uganda: return L10n.Localizable.BrowsingCountry.uganda
        case .ukraine: return L10n.Localizable.BrowsingCountry.ukraine
        case .unitedArabEmirates: return L10n.Localizable.BrowsingCountry.unitedArabEmirates
        case .unitedKingdom: return L10n.Localizable.BrowsingCountry.unitedKingdom
        case .unitedStates: return L10n.Localizable.BrowsingCountry.unitedStates
        case .unitedStatesMinorOutlyingIslands: return L10n.Localizable.BrowsingCountry.unitedStatesMinorOutlyingIslands
        case .uruguay: return L10n.Localizable.BrowsingCountry.uruguay
        case .uzbekistan: return L10n.Localizable.BrowsingCountry.uzbekistan
        case .vanuatu: return L10n.Localizable.BrowsingCountry.vanuatu
        case .venezuela: return L10n.Localizable.BrowsingCountry.venezuela
        case .vietnam: return L10n.Localizable.BrowsingCountry.vietnam
        case .virginIslandsBritish: return L10n.Localizable.BrowsingCountry.virginIslandsBritish
        case .virginIslandsUS: return L10n.Localizable.BrowsingCountry.virginIslandsUS
        case .wallisAndFutuna: return L10n.Localizable.BrowsingCountry.wallisAndFutuna
        case .westernSahara: return L10n.Localizable.BrowsingCountry.westernSahara
        case .yemen: return L10n.Localizable.BrowsingCountry.yemen
        case .zambia: return L10n.Localizable.BrowsingCountry.zambia
        case .zimbabwe: return L10n.Localizable.BrowsingCountry.zimbabwe
        }
    }
}
// swiftlint:enable line_length
