name: CI
on:
  push:
    branches: [main]
env:
  DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show Xcode list
        run: ls /Applications | grep 'Xcode'
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Xcode build
        run: xcodebuild
          -scheme DemoApp -sdk iphonesimulator -configuration Debug
          -destination 'platform=iOS Simulator,name=iPhone 12'
          build
      - name: Run tests
        run: xcodebuild
          -scheme DemoApp -sdk iphonesimulator
          -destination 'platform=iOS Simulator,name=iPhone 12'
          clean test
