name: CI
on:
  push:
    branches: [test/CI]
env:
  DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
jobs:
  Build-and-test:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show Xcode list
        run: ls /Applications | grep 'Xcode'
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Cache Swift packages
        uses: actions/cache@v2
        with:
          path: SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('EhPanda.xcodeproj/project.xcworkspace/ xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-
      - name: Xcode build
        run: xcodebuild
          -scheme EhPanda -sdk iphonesimulator -configuration Debug
          -destination 'platform=iOS Simulator,name=iPhone 12'
          -clonedSourcePackagesDirPath SourcePackages
          build
      - name: Run tests
        run: xcodebuild
          -scheme EhPanda -sdk iphonesimulator
          -destination 'platform=iOS Simulator,name=iPhone 12'
          clean test
