name: CI
on: [push, pull_request]
env:
   XCODE_VERSION: '13.0'
jobs:
  Build-and-test:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select --switch /Applications/Xcode_${{ env.XCODE_VERSION }}.app
      - name: Xcode build
        run: xcodebuild
          -scheme EhPanda -sdk iphonesimulator -configuration Debug
          -destination 'platform=iOS Simulator,name=iPhone 12'
          -clonedSourcePackagesDirPath SourcePackages
          build
      - name: Run tests
        run: xcodebuild
          -scheme EhPanda -sdk iphonesimulator
          -clonedSourcePackagesDirPath SourcePackages
          -destination 'platform=iOS Simulator,name=iPhone 12'
          clean test
