name: CI
on:
  push:
    branches: [test/CI]
jobs:
  Build-and-test:
    runs-on: macos-11
    strategy:
      matrix:
        xcode: ["13.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Select Xcode
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Cache Swift packages
        uses: actions/cache@v2
        with:
          path: SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: | 
            ${{ runner.os }}-spm-
      - name: Cache DerivedData
        uses: actions/cache@v2
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}_derived_data-xcode_${{ matrix.xcode }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.platform }}_derived_data
      - name: Xcode build
        run: xcodebuild
          -scheme EhPanda -sdk iphonesimulator -configuration Debug
          -destination 'platform=iOS Simulator,name=iPhone 12'
          -clonedSourcePackagesDirPath SourcePackages
          build
      - name: Run tests
        run: xcodebuild
          -scheme EhPanda -sdk iphonesimulator
          -destination 'platform=iOS Simulator,name=iPhone 12'
          clean test
