name: Xcode Dependencies
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  dependencies:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
      - name: Resolve Dependencies
        id: resolution
        uses: GetSidetrack/action-xcodeproj-spm-update@0.3.0
        with:
          forceResolution: true
          failWhenOutdated: false
          xcodePath: '/Applications/Xcode_16.2.app'
      - name: Create Pull Request
        if: steps.resolution.outputs.dependenciesChanged == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          branch: 'update-dependencies'
          delete-branch: true
          commit-message: 'Update dependencies [skip test]'
          title: 'Updated Dependencies'
