name: Test2
on: 
  pull_request:
    branches:
      - test/merge
    types: [closed]
env:
   SCHEME_NAME: 'EhPanda'
   DEVELOPER_DIR: /Applications/Xcode_13.0.app
   FILTER_PATH: './EngFilter'
   TEST_VERSION: 'v1.0.0'
jobs:
  Test2:
    runs-on: macos-11
    if: github.event.pull_request.merged == true && github.event.pull_request.user.login == 'tatsuz0u'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve data
        id: retrieve-data
        run: |
          sudo chmod 777 $FILTER_PATH
          echo "::set-output name=notes::$($FILTER_PATH "${{ github.event.pull_request.body }}")"
      - name: Validate data
        run: |
          [[ ! -z "${{ steps.retrieve-data.outputs.notes }}" ]] || exit 1
      - name: Get replaced body
        id: replaced-body
        run: |
         sudo chmod 777 ./EngFilter
         echo "$(./EngFilter "${{ github.event.pull_request.body }}")"
         echo "::set-output name=body::$(./EngFilter "${{ github.event.pull_request.body }}")"
      - name: Post release notes
        run: |
         curl https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
         -d parse_mode=markdown -d chat_id=${{ secrets.TELEGRAM_CHANNEL_ID_TEST }} \
         -d text='*${{ env.TEST_VERSION }} Release Notes:*%0A${{ github.event.pull_request.body }}'

         curl ${{ secrets.DISCORD_WEBHOOK_TEST }} \
         -F 'payload_json={"content": "**${{ env.TEST_VERSION }} Release Notes:**\n${{ steps.replaced-body.outputs.body }}"}'
