name: Test2
on: 
  pull_request:
    branches:
      - test/merge
    types: [closed]
env:
   SCHEME_NAME: 'EhPanda'
   DEVELOPER_DIR: /Applications/Xcode_13.0.app
   TEST_VERSION: 'v1.0.0'
jobs:
  Test2:
    runs-on: macos-11
    if: github.event.pull_request.merged == true && github.event.pull_request.user.login == 'tatsuz0u'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get replaced body
        id: replaced-body
        run: |
         sudo chmod 777 ./EngFilter
         before="
         1. Fixed UI transition issue when HUD shows up too soon after the app launched.
         アプリ起動直後にHUDが現れるとトランジションアニメーションが壊れる問題を修正。
         修復了App啓動後HUD太快出現時發生的transition動畫異常問題。

         2. Fixed detects link from clipboard feature loading takes forever issue.
         クリップボードからリンク探知機能の読み込みが終わらない問題を修正。
         修復了從剪切板檢測鏈接功能的無限加載問題。
         "
         echo "print before"
         echo "$before"
         echo "print before end"
         after=$(./EngFilter "$before")
         echo "::set-output name=body::$after"
      - name: Post release notes
        run: |
         curl https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
         -d parse_mode=markdown -d chat_id=${{ secrets.TELEGRAM_CHANNEL_ID_TEST }} \
         -d text='*${{ env.TEST_VERSION }} Release Notes:*%0A${{ steps.replaced-body.outputs.body }}'

         curl ${{ secrets.DISCORD_WEBHOOK_TEST }} \
         -F 'payload_json={"username": "Tatsuzou", "content": "**${{ env.TEST_VERSION }} Release Notes:**\n${{ steps.replaced-body.outputs.body }}"}'
